Add pending-changes CLI command
compozed/ops_manager_cli pull request #26
Opened 2017-06-08 16:27 UTC by RMeharg

Adding pending-changes to the CLI to make it easier to check for pending changes in Ops Manager and lists the GUIDs of products with pending changes.

2017-07-24 16:21 UTC, bonzofenix commented
can you sign the CLA? @RMeharg

2017-07-24 16:23 UTC, bonzofenix requested changes
Bumping the ruby version is not a requirement for the feature you are trying to add. Can we remove this commit from the PR?
Thanks

2017-07-24 19:21 UTC, RMeharg commented
Changes made, ruby version commit removed

2017-07-29 03:20 UTC, bonzofenix approved these changes

2017-07-29 03:20 UTC, merged